# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='Post',
        ),
    ]
